In [1]:
%%javascript

Jupyter.keyboard_manager.command_shortcuts.add_shortcut('r', {
    help : 'run all cells',
    help_index : 'zz',
    handler : function (event) {
        IPython.notebook.execute_cell_range(0, IPython.notebook.get_selected_index()+1);
        return false;
    }}
);

<IPython.core.display.Javascript object>

In [2]:
import pytest
import ipytest

ipytest.config(rewrite_asserts=True, magics=True)

__file__ = 'linear_geometry_numpy.ipynb' 

/home/mdexet/Workdir/EUCLID/WorkshopPythonCpp/Python-pytest/venv/lib/python3.6/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/home/mdexet/Workdir/EUCLID/WorkshopPythonCpp/Python-pytest/venv/lib/python3.6/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [4]:
import numpy as np

theta = np.radians(30)

r = np.array(( (np.cos(theta), -np.sin(theta)),
               (np.sin(theta),  np.cos(theta)) ))

print('rotation matrix:')
print(r)

v = np.array((0,1))

print('vector v: ')
print(v)

print('apply the rotation matrix r to v: r*v')
print( r.dot(v) )

rotation matrix:
[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
vector v: 
[0 1]
apply the rotation matrix r to v: r*v
[-0.5        0.8660254]


In [5]:
a=np.array((0,1))
b=np.array((1,0))

np.vdot(a,b)

0

In [18]:
np.dot(a,b)

0

In [6]:
np.cross(a,b)

array(-1)

In [7]:
np.cross(b,a)

array(1)

In [8]:
def new_rotation_matrix(theta):
    r = np.array(( (np.cos(theta), -np.sin(theta)),
               (np.sin(theta),  np.cos(theta)) ))
    return r

In [9]:
a.dot(new_rotation_matrix(np.pi/2))

array([1.000000e+00, 6.123234e-17])

In [10]:
new_rotation_matrix(np.pi/2).dot(a)

array([-1.000000e+00,  6.123234e-17])

In [17]:
c = np.array((5,5))
c/np.linalg.norm(c)    

array([0.70710678, 0.70710678])